version: '3.3'

services:
  facebook_db:
    container_name: 'facebook_db'
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=facebook
    networks: 
      - facebook_network

  facebook_backend:
    container_name: 'facebook_backend'
    build: 
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./:/usr/app
    ports:
      - 3000:3000
    networks: 
      - facebook_network
    depends_on:
      - facebook_db

networks:
  facebook_network:

volumes:
  pg_data:
