version: '3.3'

services:
  facebook_db:
    container_name: 'facebook_db'
    image: postgres
    environment:
      POSTGRES_DB: facebook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pg_data:
